name: Run JMeter Tests

on:
  push:
    branches:
      - main  # Run the workflow when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Run the workflow when a pull request is opened or synchronized for the main branch

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Run JMeter Tests
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xf apache-jmeter-5.5.tgz
        cd apache-jmeter-5.5/bin
        ./jmeter -n -t D:/apache-jmeter-5.5/bin/Ringkasan Materi/Mix Create Update Bilpay.jmx -l results.jtl
      working-directory: ${{ github.workspace }}
