name: JMeter Test

on:
  push:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install JMeter
      run: |
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.5.tgz
        tar -xzf apache-jmeter-5.5.tgz
      working-directory: ${{ github.workspace }}

    - name: Run JMeter Test
      run: |
        ./apache-jmeter-5.5/bin/jmeter -n -t Mix Create Update Bilpay.jmx -l results.jtl
      working-directory: ${{ github.workspace }}

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: jmeter-results
        path: results.jtl
